# Site settings
title: JosueDanielBust - Blog
email: josuedanielbustamante@gmail.com
description: Web Developer &amp; Young Entrepreneur by Passion - Coffee Lover - //Coderiser - Maker networks - Medellín Director at @coderiseorg
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://josuedanielbust.com" # the base hostname & protocol for your site
twitter_username: JosueDanielBust
github_username:  JosueDanielBust

# Build settings
markdown: kramdown
permalink: /blog/:year-:month/:title.html
paginate: 10
paginate_path: "/blog/page:num/"
gems: 
  - jekyll-paginate
  - jekyll-sitemap
#  - youtube

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Collections
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/

# Defaults values
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      post: true
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: category_list