# Site settings
title: JosueDanielBust - Blog
email: josuedanielbustamante@gmail.com
description: Coffee Lover - Web Developer &amp; Young Entrepreneur by Passion - Volunteer at Coderise &amp; AIESEC
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://josuedanielbust.com" # the base hostname & protocol for your site
twitter_username: JosueDanielBust
github_username:  JosueDanielBust

# Build settings
markdown: kramdown
permalink: /blog/:year-:month/:title.html
paginate: 10
paginate_path: "/blog/page:num/"
plugins: [jekyll-paginate, jekyll-sitemap]

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Collections
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  multiverse:
    output: true
    permalink: /multiverse/:slug.html

# Defaults values
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      post: true
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: category_list
  -
    scope:
      path: ""
      type: multiverse
    values:
      layout: multiverse_chapter
