# Site settings
title: JosueDanielBust - Blog
email: josuedanielbustamante@gmail.com
description: Web Developer &amp; Young Entrepreneur by Passion - Coffee Lover - //CodeRiser - Maker networks - Medellín Director at @Code_rise
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://josuedanielbust.com" # the base hostname & protocol for your site
twitter_username: JosueDanielBust
github_username:  JosueDanielBust

# Build settings
markdown: kramdown
permalink: /blog/:year-:month/:title.html
paginate: 10
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate]
#gems: [jekyll-paginate, font_awesome, reading_time, youtube]

# Categories
category_dir: /blog/categories